/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "SendblueApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendblueApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendblueFromNumber": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendblueVerifiedContact": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WatchStateBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Watcher": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}